# This is a basic workflow to help you get started with Actions

name: CI
defaults:
  run:
    shell: bash
env:
  image: gtaapi
  path: /projetos/

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    environment: SSH
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Instalação SSH Client
        run: sudo apt update &&
             sudo apt install openssh-client sshpass -y

      - name: Atualização do projeto
        run: sshpass -v -p ${{ secrets.PASSWD }} ssh -o "StrictHostKeyChecking no"
             mac@docker.macsolucoes.com "cd ${{ env.path }}${{ env.image }} && git pull -f "

      # - name: Buildar nova imagem
      #   run: sshpass -v -p ${{ secrets.PASSWD }} ssh
      #        mac@docker.macsolucoes.com "docker build ${{ env.path }}${{ env.image }}/container/. -t ${{ env.image }} "

      # - name: Executar nova imagem
      #   run: sshpass -v -p ${{ secrets.PASSWD }} ssh
      #        mac@docker.macsolucoes.com "docker run -d --name ${{ env.image }} -v ${{ env.path }}${{ env.image }}:/code -p 8081:80  ${{ env.image }}"

      # - name: Atuallizar bibliotecas
      #   run: sshpass -v -p ${{ secrets.PASSWD }} ssh
      #        mac@docker.macsolucoes.com "docker exec ${{ env.image }} /code/composer.sh "

