# This is a basic workflow to help you get started with Actions

name: CI
defaults:
  run: 
    shell: bash
    
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Instalação SSH Client
        run: sudo apt update && 
             sudo apt install openssh-client sshpass -y 
             
      - name: Teste ssh
        run: echo 'sshpass -v -p $PASSWD ssh -o "StrictHostKeyChecking no" mac@docker.macsolucoes.com "ls -lh /"'
          
