# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Instalação SSH Client
        run: sudo apt update && sudo apt install openssh-client sshpass -y 
        
      - name: Acesso Docker
        run: sshpass -v -p $SSHPasswd ssh mac@docker.macsolucoes.com "ls -lh"
          
