# This is a basic workflow to help you get started with Actions

name: CI
defaults:
  run: 
    shell: bash
env: 
  image: gtaapi
  path: /projetos/

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    environment: SSH
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Instalação SSH Client
        run: sudo apt update && 
             sudo apt install openssh-client sshpass -y 
             
      - name: Atualização do projeto
        run: sshpass -v -p ${{ secrets.PASSWD }} ssh -o "StrictHostKeyChecking no" 
             mac@docker.macsolucoes.com "cd ${{ env.path }}${{ env.image }} && git pull -f && 
             cd container && composer update"
      
      - name: Atualização bibliotecas
        run: sshpass -v -p ${{ secrets.PASSWD }} ssh -o "StrictHostKeyChecking no" 
             mac@docker.macsolucoes.com "cd ${{ env.path }}${{ env.image }} && composer update"
      
      - name: Buildar nova imagem
        run: sshpass -v -p ${{ secrets.PASSWD }} ssh -o "StrictHostKeyChecking no" 
             mac@docker.macsolucoes.com "docker build ${{ env.path }}${{ env.image }}/container/. "
          
